arb-dir: lib/l10n
template-arb-file: intl_en_US.arb
output-localization-file: app_localizations.dart
translate: true
generate: true
key-prefix: AppLocalizations.of(context)!.
auto-name-key: true
key-name-language: en_US
import-line: ""